reverse-suggestionsWhitelist: false
suggestionsWhitelist:
  - bal
  - balance
  - money
  - togglefm
  - filteredmsgs
  - filtered
  - fm
  - togglesc
  - sctoggle
  - tsc
  - sct
  - toggletac
  - hush
  - gm
  - gamemode
  - kick
  - gmc
  - gms
  - vanish
  - v
  - tp
  - teleport
  - msg
  - message
  - m
  - tell
  - t
  - whisper
  - w
  - r
  - reply
  - togglepm
  - fly
  - list
  - broadcast
  - bc
  - mod
  - eventbc
  - eventtitle
  - titlebroadcast
  - donation
  - rank
  - silence
  - chatslow
  - delay
  - setmaxplayers
  - maxplayers
  - toggletp
  - msgto
  - msgtoall
  - speed
  - flyspeed
  - walkspeed
  - blockaccess
  - joinalert
  - rankcrate
  - ec
  - enderchest
  - workbench
  - wb
  - toggletag
  - glowtoggle
  - vote
  - votelinks
  - storerank
  - chargebacknotify
  - wintercratebc
  - punishbook
  - heal
  - feed
  - pluscolor
  - pull
  - baltop
  - ebaltop
  - balancetop
  - pvpban
  - newyearstitle
  - newyearsbc
  - craft
  - serverinfo
  - cps
  - network
  - playtimexp
  - playtimecoins
  - reportacceptmsg
  - reportdeniedmsg
  - port
  - d
  - eventsnpc
  - chatfilter
  - violation
  - convert
  - playtimereward
  - voterewards
  - updatenotify
  - recentupdatesbook
  - addmysqlstore
  - removemysqlstore
  - news
  - gift
  - testgift
  - pay
  - updatestore
  - togglegifting
  - storecrystals
  - updatestoresale
  - doublerewardsevent
  - fridayevent
  - playerinfo
  - toggleupdatebook
  - togglestatusnotify
  - toggletacnotify
  - togglegift
  - newplayerbook
  - playernews
  - disable
  - toggleblock
  - toggleafkvanish
  - toggledevmode
  - menu
  - tags
  - kits
  - ts
  - tokens
  - tokenshop
  - quests
  - tiers
  - ranks
  - settings
  - deluxecosmetics
  - cosmetics
  - warps
  - stats
  - statistics
  - ah
  - auction
  - home
  - sethome
  - delhome
  - shop
  - crates
  - jobs
  - ptime
  - pweather
  - near
  - hat
  - condense
  - depth
  - darkauction
  - crystals
  - coins
  - hosttokens
  - srestart
  - saferestart
  - killeffects
  - boweffects
  - deatheffects
  - lands
  - backpack
  - pwarp
  - pwarps
  - playerwarps
  - playerwarp
  - bank
  - report
  - chatreport
  - wild
  - rtp
  - spawn
  - vp
  - voteparty
  - trade
  - history
  - ph
  - checkhistory
  - myhistory
  - punishhistory
  - punishments
  - bans
  - mutes
  - warns
  - warnings
  - clearhistory
  - cleanhistory
  - ch
  - ban
  - tempban
  - mute
  - tempmute
  - warn
  - userinfo
  - tacban
  - tactempban
  - asa
  - asatemp
  - eventprogress
  - staffchat
  - sc
  - adminchat
  - ac
  - tac
  - warp
  - warps
  - events
  - rewards