################################################################################
#
# THIS PLUGIN IS MADE FOR USE ON TWISTEDMC
# DO NOT USE ON YOUR OWN SERVER TO TEST USE THE DEV SERVER
# DO NOT DISTRIBUTE
#
# PA Pre Alpha
# A Alpha
# B Beta
# H Halloween
# C Christmas
# AC Advent Calendar
# API `Util.API` Class version
# Use 'Bugfix #<#>' for bug fixes that do not fit into one of the above catagories
#
################################################################################

name: EventCore1.17
version: H0.9.6|C0.0.8|AC0.0.4|API0.1.0
author: [shastagrande,MCEpic_Nation]
main: net.twistedmc.events.Main
api-version: 1.16
website: https://twistedmc.net
depend: [PlaceholderAPI, EnchantedCore]
commands:
  eventprogress:
  rewards:
  hcc:
  seasonal:
  candy:
   aliases: [candystore]
  adventcalendar:
   aliases: [calendar]